In [ ]:
import pandas as pd
import numpy as np 
import torch
import torch.nn as nn

In [6]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("fedesoriano/cifar10-python-in-csv")

print("Path to dataset files:", path)

d:\Programming\Learn_Pytorch_for_deep_learning\.env\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.12), please consider upgrading to the latest version (0.3.13).
Downloading from https://www.kaggle.com/api/v1/datasets/download/fedesoriano/cifar10-python-in-csv?dataset_version_number=1...

100%|██████████| 209M/209M [00:53<00:00, 4.06MB/s]

Extracting files...

Path to dataset files: C:\Users\sande\.cache\kagglehub\datasets\fedesoriano\cifar10-python-in-csv\versions\1

In [7]:
import os 

print("Dictionary:- ",os.listdir(path))

Dictionary:-  ['batches.meta', 'test.csv', 'train.csv']

In [8]:
#  1. Create an empty list to hold the individual DataFrames
list_of_dataframes = []

# 2. Loop through each file in the directory
for filename in os.listdir(path):
    # 3. Check if the file is a CSV
    if filename.endswith('.csv'):
        # 4. Construct the full path to the file
        # os.listdir() only gives the filename, not the full path
        full_path = os.path.join(path, filename)
        
        # 5. Read the CSV into a DataFrame and append it to your list
        df_temp = pd.read_csv(full_path)
        list_of_dataframes.append(df_temp)

In [14]:
test_df=list_of_dataframes[0]
train_df=list_of_dataframes[1]


test_df.head()

,pixel_0,pixel_1,pixel_2,pixel_3,pixel_4,pixel_5,pixel_6,pixel_7,pixel_8,pixel_9,...,pixel_3062,pixel_3063,pixel_3064,pixel_3065,pixel_3066,pixel_3067,pixel_3068,pixel_3069,pixel_3070,pixel_3071
0,158,159,165,166,160,156,162,159,158,159,...,130,123,145,167,182,175,145,124,129,110
1,235,231,232,232,232,232,232,232,232,232,...,108,117,123,133,141,153,163,178,191,199
2,158,158,139,132,166,182,187,193,199,205,...,45,46,44,44,43,52,37,8,3,7
3,155,167,176,190,177,166,168,166,170,179,...,52,55,70,103,105,72,53,50,52,50
4,65,70,48,30,23,40,44,45,45,40,...,102,127,156,139,131,130,147,136,146,117

In [15]:
train_df.head()

,pixel_0,pixel_1,pixel_2,pixel_3,pixel_4,pixel_5,pixel_6,pixel_7,pixel_8,pixel_9,...,pixel_3063,pixel_3064,pixel_3065,pixel_3066,pixel_3067,pixel_3068,pixel_3069,pixel_3070,pixel_3071,label
0,59,43,50,68,98,119,139,145,149,149,...,58,65,59,46,57,104,140,84,72,6
1,154,126,105,102,125,155,172,180,142,111,...,42,67,101,122,133,136,139,142,144,9
2,255,253,253,253,253,253,253,253,253,253,...,83,80,69,66,72,79,83,83,84,9
3,28,37,38,42,44,40,40,24,32,43,...,39,59,42,44,48,38,28,37,46,4
4,170,168,177,183,181,177,181,184,189,189,...,88,85,82,83,79,78,82,78,80,1

In [17]:
import matplotlib.pyplot as plt

In [20]:
X_train=train_df.iloc[:,1:].values
y_train=train_df.iloc[:,0].values

# for test 

X_test=test_df.iloc[:,1:].values
y_test=test_df.iloc[:,0].values

In [21]:
X_train.shape

(50000, 3072)